"""Add project size settings and update project model

Revision ID: 7d0a7d8f248d
Revises: d19a5bc4db8c
Create Date: 2025-10-02 12:08:23.632259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d0a7d8f248d'
down_revision: Union[str, None] = 'd19a5bc4db8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first
    worktype_enum = sa.Enum('DISCRETE_PROJECT', 'CAMPAIGN', name='worktype')
    worktype_enum.create(op.get_bind(), checkfirst=True)

    processtype_enum = sa.Enum('CONVENTIONAL', 'PHASE_GATE', name='processtype')
    processtype_enum.create(op.get_bind(), checkfirst=True)

    # Create project_size_settings table
    op.create_table('project_size_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('small_min_hours', sa.Integer(), nullable=False),
    sa.Column('small_max_hours', sa.Integer(), nullable=False),
    sa.Column('medium_min_hours', sa.Integer(), nullable=False),
    sa.Column('medium_max_hours', sa.Integer(), nullable=False),
    sa.Column('large_min_hours', sa.Integer(), nullable=False),
    sa.Column('large_max_hours', sa.Integer(), nullable=False),
    sa.Column('phase_gate_recommendation_hours', sa.Integer(), nullable=False),
    sa.Column('auto_adjust_project_size', sa.Boolean(), nullable=True),
    sa.Column('warn_on_size_mismatch', sa.Boolean(), nullable=True),
    sa.Column('recommend_phase_gate', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('is_active')
    )

    op.alter_column('deliverable_templates', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('projects', sa.Column('work_type', worktype_enum, server_default='DISCRETE_PROJECT', nullable=False))
    op.add_column('projects', sa.Column('process_type', sa.Enum('CONVENTIONAL', 'PHASE_GATE', name='processtype'), nullable=True))
    op.add_column('projects', sa.Column('process_type_recommended', sa.Enum('CONVENTIONAL', 'PHASE_GATE', name='processtype'), nullable=True))
    op.add_column('projects', sa.Column('process_type_overridden', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('campaign_duration_months', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('campaign_service_level', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('campaign_site_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('campaign_response_requirement', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('campaign_monthly_hours', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('campaign_scheduled_deliverables', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('campaign_pricing_model', sa.String(length=50), nullable=True))
    op.alter_column('projects', 'size',
               existing_type=postgresql.ENUM('SMALL', 'MEDIUM', 'LARGE', 'skid', 'PHASE_GATE', name='projectsize'),
               nullable=True)
    op.create_index(op.f('ix_projects_work_type'), 'projects', ['work_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_work_type'), table_name='projects')
    op.alter_column('projects', 'size',
               existing_type=postgresql.ENUM('SMALL', 'MEDIUM', 'LARGE', 'skid', 'PHASE_GATE', name='projectsize'),
               nullable=False)
    op.drop_column('projects', 'campaign_pricing_model')
    op.drop_column('projects', 'campaign_scheduled_deliverables')
    op.drop_column('projects', 'campaign_monthly_hours')
    op.drop_column('projects', 'campaign_response_requirement')
    op.drop_column('projects', 'campaign_site_count')
    op.drop_column('projects', 'campaign_service_level')
    op.drop_column('projects', 'campaign_duration_months')
    op.drop_column('projects', 'process_type_overridden')
    op.drop_column('projects', 'process_type_recommended')
    op.drop_column('projects', 'process_type')
    op.drop_column('projects', 'work_type')
    op.alter_column('deliverable_templates', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###