"""add_rate_entries_to_rate_sheets

Revision ID: d19a5bc4db8c
Revises: dbe9959cb2f2
Create Date: 2025-10-01 23:07:33.698933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19a5bc4db8c'
down_revision: Union[str, None] = 'dbe9959cb2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_sheets', sa.Column('rate_entries', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_sheets', 'rate_entries')
    # ### end Alembic commands ###