"""Add client_complexity and base_contingency to companies

Revision ID: dbe9959cb2f2
Revises: 7fec0a6b4c61
Create Date: 2025-10-01 22:45:01.899028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe9959cb2f2'
down_revision: Union[str, None] = '7fec0a6b4c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('client_complexity', sa.Integer(), nullable=True, server_default='5'))
    op.add_column('companies', sa.Column('base_contingency', sa.Float(), nullable=True, server_default='15.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'base_contingency')
    op.drop_column('companies', 'client_complexity')
    # ### end Alembic commands ###