"""add phase gate fields to projects

Revision ID: ed1b294f2768
Revises: 9afa914e74c6
Create Date: 2025-09-30 20:10:04.981942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1b294f2768'
down_revision: Union[str, None] = '9afa914e74c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ProjectPhase enum type
    projectphase_enum = sa.Enum('FRAME', 'SCREEN', 'REFINE', 'IMPLEMENT', name='projectphase')
    projectphase_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('deliverables', sa.Column('expected_sheets', sa.Integer(), nullable=True))
    op.add_column('deliverables', sa.Column('actual_sheets', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('current_phase', projectphase_enum, nullable=True))
    op.add_column('projects', sa.Column('phase_completion', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('gate_approvals', sa.JSON(), nullable=True))
    op.alter_column('projects', 'overhead_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'overhead_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('projects', 'gate_approvals')
    op.drop_column('projects', 'phase_completion')
    op.drop_column('projects', 'current_phase')
    op.drop_column('deliverables', 'actual_sheets')
    op.drop_column('deliverables', 'expected_sheets')

    # Drop the ProjectPhase enum type
    sa.Enum(name='projectphase').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###