"""Add client complexity and base contingency to companies

Revision ID: 2de4ce3ea74a
Revises: 633087174796
Create Date: 2025-10-01 22:27:54.653767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2de4ce3ea74a'
down_revision: Union[str, None] = '633087174796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_client_templates_id'), 'client_templates', ['id'], unique=False)
    op.add_column('companies', sa.Column('client_complexity', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('base_contingency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'base_contingency')
    op.drop_column('companies', 'client_complexity')
    op.drop_index(op.f('ix_client_templates_id'), table_name='client_templates')
    op.alter_column('client_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###